# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liffey House
# email: blair.shotlow@googlemail.com
description: Our House in Austin,TX
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

permalink: pretty
#permalink: /blog/:year/:month/:day/:title

#Ideal Image Slider
slider_array: []

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"

gems:
  - jemoji
